### PR TITLE
Issue522: Capture is failing in tests in 9.20

### PR DESCRIPTION
**Pull request by ASHNA-AGGARWAL-KEYSIGHT**
resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/522

### CODE REVIEW

**Review by ajbalogh — COMMENTED** [review]
Does this change fulfill the capture config format that is in the model? 
The model allows for both pcap and pcapng - should we be supporting both?

**Comment by ANISH-GOTTAPU** [comment]
@ajbalogh : We are not going to merge the PR associated with this, We would like to know if anything else is breaking with 9.20. The issue is just a place holder for capture issue related to ixN 9.20

**Comment by ASHNA-AGGARWAL-KEYSIGHT** [comment]
Have change it to draft to avoid confusion

**Comment by ANISH-GOTTAPU** [comment]
@ajbalogh : We had internal discussion and thought of moving CI/CD to 9.20. Though 9.20 supports only pcapng, we will raise a warning with snappi-ixnetwork that pcap is not supported. 

There is another discussion that is happening with Mario(IxNetwork Analyzer Team) and we have to take a call whether to keep the support in models or not based on conclusion.

@ankur-sheth & @ashutshkumr : FYI

**Pull request merged**
